#!/bin/sh

set -e

DAEMON="/container/dist/sbin/nginx"
NAME="nginx"
PATH="/container/dist/sbin:/container/dist/bin:/sbin:/bin:/usr/sbin:/usr/bin"
LOGFILE="/var/log/"${NAME}".log"
CHROOT="/var/run/"${NAME}"/empty"

test -x "${DAEMON}" || exit 0

. /lib/lsb/init-functions

if [ ! -e "${LOGFILE}" ]
then
  touch "${LOGFILE}"
  chmod 640 "${LOGFILE}"
  chown root:adm "${LOGFILE}"
fi

if [ ! -d "${CHROOT}" ]
then
  mkdir -p "${CHROOT}"
fi

case "${1}" in
  start)
    _PID=`ps -ef | awk '/\/container\/dist\/sbin\/nginx/{print $2}'`
    if [ ! -z "$_PID" ]
    then
      echo "Nginx Already Running with PID $_PID"
      exit 1
    fi
    log_daemon_msg "Starting" "${NAME}"
    
    ${DAEMON} 
    

    n=0
    while [ ${n} -le 5 ]
    do 
      _PID=`ps -ef | awk '/\/container\/dist\/sbin\/nginx/{print $2}'` 

      if [ ! -z "$_PID" ]
      then
        break
      fi
      sleep 1
      n=$(( $n + 1 ))
    done

    if [ -z "$_PID" ]
    then
      log_daemon_msg "${NAME} failed - probably invalid config."
      # exit 1
    else
      log_daemon_msg "Nginx Running with PID $_PID"
    fi

    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stoping" "${NAME}"

    ${DAEMON} -s stop
    ;;
  restart)
    ${0} stop
    ${0} start
    ;;

  reload|force-reload)
    log_daemon_msg "Reloading Nginx"

    $DAEMON -s reload

    log_end_msg "${?}"
    ;;

  status)
    _PID=`ps -ef | awk '/\/container\/dist\/sbin\/nginx/{print $2}'`
    if [ -z "$_PID" ]
    then
      log_daemon_msg "${NAME} is not Running"
      # exit 1
    else
      log_daemon_msg "Nginx Running with PID $_PID"
    fi
    log_end_msg "${?}"
    
    ;;

  *)
    echo "Usage: ${0} {start|stop|restart|reload|status}"
    exit 1
    ;;
esac
