#!/bin/sh

### BEGIN INIT INFO
# Provides:   php-fpm

#     for security.
### END INIT INFO

set -e

DAEMON="/container/dist/sbin/nginx"
NAME="nginx"
PATH="/container/dist/sbin:/container/dist/bin:/sbin:/bin:/usr/sbin:/usr/bin"
LOGFILE="/var/log/"${NAME}".log"
CHROOT="/var/run/"${NAME}"/empty"

test -x "${DAEMON}" || exit 0

. /lib/lsb/init-functions

if [ ! -e "${LOGFILE}" ]
then
  touch "${LOGFILE}"
  chmod 640 "${LOGFILE}"
  chown root:adm "${LOGFILE}"
fi

if [ ! -d "${CHROOT}" ]
then
  mkdir -p "${CHROOT}"
fi

case "${1}" in
  start)
    log_daemon_msg "Starting" "${NAME}"
    
    ${DAEMON} 
    
     

    if ! ps -C "${NAME}" 
    then
      log_warning_msg "${NAME} failed - probably invalid config."
      exit 1
    fi

    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stoping" "${NAME}"

    ${DAEMON} -s stop
    ;;
  restart)
    ${0} stop
    ${0} start
    ;;

  reload|force-reload)
    log_daemon_msg "Reloading Nginx"

    $DAEMON -s reload

    log_end_msg "${?}"
    ;;

  status)
    ps -C "${NAME}"
    ;;

  *)
    echo "Usage: ${0} {start|stop|restart|reload|status}"
    exit 1
    ;;
esac
