#! /bin/sh
PATH="/container/dist/sbin:/container/dist/bin:/sbin:/bin:/usr/sbin:/usr/bin"
# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting pgsql 10"
    sudo -u postgres bash -c  "/container/dist/pgsql/bin/pg_ctl -D /container/dist/pgsql_data/10/main -l /tmp/logfile start"
    ;;
  stop)
    echo "Stopping pgsql 10"
    sudo -u postgres bash -c  "/container/dist/pgsql/bin/pg_ctl -D /container/dist/pgsql_data/10/main -l /tmp/logfile stop"

    sleep 2
    ;;
  *)
    echo "Usage: /container/dist/etc/init.d/pgsql {start|stop}"
    exit 1
    ;;
esac

exit 0