#!/bin/sh



set -e


DAEMON="/container/dist/www/html/push-server/npx-nodemon.sh"
NAME="npx-nodemon.sh"
PATH="/container/dist/sbin:/container/dist/bin:/sbin:/bin:/usr/sbin:/usr/bin"
LOGFILE="/var/log/$NAME.log"
CHROOT="/var/run/$NAME/empty"

test -x "${DAEMON}" || exit 0

. /lib/lsb/init-functions

 

case "${1}" in
  start)
    log_daemon_msg "Starting Push Server Port 7000" "${NAME}"

   

    start-stop-daemon --start --background -m --oknodo --pidfile /var/run/dev-server.pid --exec ${DAEMON}
    
    
    _PID="$(ps aux | grep nodemon|awk '{print $2}')"
    # echo $_PID; 
    for pid in $_PID
      do echo "$NAME Running with PID $pid"

    done

    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stopping Push Server Port 7000" "${NAME}"
    
    _PID=$(ps aux | grep nodemon|awk '{print $2}')
    for pid in $_PID
      do kill $pid
    done
    ;;

  restart)
    ${0} stop
    ${0} start
    ;;

   

  status)
    echo "${DAEMON}" "Push Server Port 7000"
    _PID="$(ps aux | grep nodemon|awk '{print $2}')"
    for pid in $_PID
      do echo "$NAME Running with PID $pid"
    done
    ;;

  *)
    echo "Usage: ${0} {start|stop|restart|status}"
    exit 1
    ;;
esac
