/*
 Navicat Premium Data Transfer

 Source Server         : localhost@gce
 Source Server Type    : PostgreSQL
 Source Server Version : 150002 (150002)
 Source Host           : localhost:5432
 Source Catalog        : postgres
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 150002 (150002)
 File Encoding         : 65001

 Date: 26/02/2023 19:19:23
*/


-- ----------------------------
-- Sequence structure for app_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."app_id_seq";
CREATE SEQUENCE "public"."app_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for telepon_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."telepon_id_seq";
CREATE SEQUENCE "public"."telepon_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for word_list_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."word_list_id_seq";
CREATE SEQUENCE "public"."word_list_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for word_list_ttf_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."word_list_ttf_id_seq";
CREATE SEQUENCE "public"."word_list_ttf_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for app
-- ----------------------------
DROP TABLE IF EXISTS "public"."app";
CREATE TABLE "public"."app" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "created_at" timestamptz(6) DEFAULT now(),
  "app_id" varchar COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for telepon
-- ----------------------------
DROP TABLE IF EXISTS "public"."telepon";
CREATE TABLE "public"."telepon" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "created_at" timestamptz(6) DEFAULT now(),
  "nama" varchar(50) COLLATE "pg_catalog"."default",
  "nomor" varchar(13) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for tts_project
-- ----------------------------
DROP TABLE IF EXISTS "public"."tts_project";
CREATE TABLE "public"."tts_project" (
  "id" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "text" text COLLATE "pg_catalog"."default",
  "word_count" int4,
  "word_list" json,
  "output_file" varchar(255) COLLATE "pg_catalog"."default",
  "name" varchar COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for word_list
-- ----------------------------
DROP TABLE IF EXISTS "public"."word_list";
CREATE TABLE "public"."word_list" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "content" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for word_list_ttf
-- ----------------------------
DROP TABLE IF EXISTS "public"."word_list_ttf";
CREATE TABLE "public"."word_list_ttf" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "content" varchar(255) COLLATE "pg_catalog"."default",
  "path" varchar(255) COLLATE "pg_catalog"."default",
  "word_id" int4
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."app_id_seq"
OWNED BY "public"."app"."id";
SELECT setval('"public"."app_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."telepon_id_seq"
OWNED BY "public"."telepon"."id";
SELECT setval('"public"."telepon_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."word_list_id_seq"
OWNED BY "public"."word_list"."id";
SELECT setval('"public"."word_list_id_seq"', 38, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."word_list_ttf_id_seq"
OWNED BY "public"."word_list_ttf"."id";
SELECT setval('"public"."word_list_ttf_id_seq"', 36, true);

-- ----------------------------
-- Primary Key structure for table app
-- ----------------------------
ALTER TABLE "public"."app" ADD CONSTRAINT "app_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table telepon
-- ----------------------------
ALTER TABLE "public"."telepon" ADD CONSTRAINT "telepon_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table tts_project
-- ----------------------------
ALTER TABLE "public"."tts_project" ADD CONSTRAINT "tts_project_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table word_list
-- ----------------------------
ALTER TABLE "public"."word_list" ADD CONSTRAINT "word_list_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table word_list_ttf
-- ----------------------------
ALTER TABLE "public"."word_list_ttf" ADD CONSTRAINT "word_list_ttf_pkey" PRIMARY KEY ("id");
